export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_START = 'GET_TAGS_START';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const GET_VIDEO_LIST = 'GET_VIDEO_LIST';
export const GET_VIDEO_LIST_START = 'GET_VIDEO_LIST_START';
export const GET_VIDEO_LIST_SUCCESS = 'GET_VIDEO_LIST_SUCCESS';

export const GET_VIDEO_DETAILS = 'GET_VIDEO_DETAILS';
export const GET_VIDEO_DETAILS_START = 'GET_VIDEO_DETAILS_START';
export const GET_VIDEO_DETAILS_SUCCESS = 'GET_VIDEO_DETAILS_SUCCESS';

export const GET_VIDEO_PLAYLIST = 'GET_VIDEO_PLAYLIST';
export const GET_VIDEO_PLAYLIST_START = 'GET_VIDEO_PLAYLIST_START';
export const GET_VIDEO_PLAYLIST_SUCCESS = 'GET_VIDEO_PLAYLIST_SUCCESS';
