export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_START = 'GET_TAGS_START';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const GET_VIDEO_LIST = 'GET_VIDEO_LIST';
export const GET_VIDEO_LIST_START = 'GET_VIDEO_LIST_START';
export const GET_VIDEO_LIST_SUCCESS = 'GET_VIDEO_LIST_SUCCESS';

export const GET_VIDEO_DETAILS = 'GET_VIDEO_DETAILS';
export const GET_VIDEO_DETAILS_START = 'GET_VIDEO_DETAILS_START';
export const GET_VIDEO_DETAILS_SUCCESS = 'GET_VIDEO_DETAILS_SUCCESS';

export const GET_VIDEO_PLAYLIST = 'GET_VIDEO_PLAYLIST';
export const GET_VIDEO_PLAYLIST_START = 'GET_VIDEO_PLAYLIST_START';
export const GET_VIDEO_PLAYLIST_SUCCESS = 'GET_VIDEO_PLAYLIST_SUCCESS';

export const ADD_VIDEO_COMMENT = 'ADD_VIDEO_COMMENT';
export const ADD_VIDEO_COMMENT_START = 'ADD_VIDEO_COMMENT_START';
export const ADD_VIDEO_COMMENT_SUCCESS = 'ADD_VIDEO_COMMENT_SUCCESS';

export const GET_VIDEO_COMMENT = 'GET_VIDEO_COMMENT';
export const GET_VIDEO_COMMENT_START = 'GET_VIDEO_COMMENT_START';
export const GET_VIDEO_COMMENT_SUCCESS = 'GET_VIDEO_COMMENT_SUCCESS';

export const GET_SEARCH = 'GET_SEARCH';
export const GET_SEARCH_START = 'GET_SEARCH_START';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';

export const GET_TAGS_DATA = 'GET_TAGS_DATA';
export const GET_TAGS_DATA_START = 'GET_TAGS_DATA_START';
export const GET_TAGS_DATA_SUCCESS = 'GET_TAGS_DATA_SUCCESS';

export const GET_CATEGORY_DATA = 'GET_CATEGORY_DATA';
export const GET_CATEGORY_DATA_START = 'GET_CATEGORY_DATA_START';
export const GET_CATEGORY_DATA_SUCCESS = 'GET_CATEGORY_DATA_SUCCESS';

export const GET_CURRENT_VIDEO_PLAYER_TIME = 'GET_CURRENT_VIDEO_PLAYER_TIME';
export const GET_CURRENT_VIDEO = 'GET_CURRENT_VIDEO';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';

export const REGISTER = 'REGISTER';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CONNECTION = 'CONNECTION';
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';

export const BETA_VERISON = 'BETA_VERISON';
