const LEARNAPP = '@main';

export const HOME = `${LEARNAPP}_HOME`;
export const SEARCH = `${LEARNAPP}_SEARCH`;
export const SETUP_KIDS = `${LEARNAPP}_SETUP_KIDS`;
export const LOGIN = `${LEARNAPP}_LOGIN`;
export const REGISTER = `${LEARNAPP}_REGISTER`;
export const VIDEO_DETAILS = `${LEARNAPP}_VIDEO_DETAILS`;
export const TAGS_WISE = `${LEARNAPP}_TAGS_WISE`;
export const CATEGORY_WISE = `${LEARNAPP}_CATEGORY_WISE`;

export const APP_NAVIGATOR = `${LEARNAPP}_APP_NAVIGATOR`;
export const INTERNET_ERROR = `${LEARNAPP}_INTERNET_ERROR`;
export const AUTH_NAVIGATOR = `${LEARNAPP}_AUTH_NAVIGATOR`;
export const HOME_NAVIGATOR = `${LEARNAPP}_HOME_NAVIGATOR`;
export const DRAWER_NAVIGATOR = `${LEARNAPP}_DRAWER_NAVIGATOR`;

export const CATEGORY = `${LEARNAPP}_CATEGORY`;
export const READ_ALOUD = `${LEARNAPP}_READ_ALOUD`;
export const NURSERY_RHYMES = `${LEARNAPP}_NURSERY_RHYMES`;
export const MANY_MORE = `${LEARNAPP}_MANY_MORE`;
export const AND_MORE = `${LEARNAPP}_AND_MORE`;
export const DRAWER = `${LEARNAPP}_DRAWER`;
